[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode"
style = "Bold"

[font.italic]
family = "FiraCode"
style = "Italic"

[font.normal]
family = "FiraCode"
style = "Regular"
